import Head from "next/head";
import Image from "next/image";
import styles from "../components/Home.module.scss";
import List from "../components/List";

export default function Home() {
	return (
		<div className={styles.page}>
			<Head>
				<title>Poke Frontend</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className={styles.logo}>
				<Image src="/pokemon-logo.svg" width="300" height="150" />
			</div>

			<main>
				<List />
			</main>
		</div>
	);
}
